class Topic {
  final String id;
  final String title;
  final String tag;
  final int likes;
  final int comments;
  final DateTime createdAt;
  final String? imageUrl;
  /// 发布人 ID（点击头像进主页）
  final String authorId;
  /// 发布人昵称
  final String authorName;
  /// 发布人头像 URL
  final String authorAvatarUrl;

  Topic({
    required this.id,
    required this.title,
    required this.tag,
    required this.likes,
    required this.comments,
    required this.createdAt,
    this.imageUrl,
    required this.authorId,
    required this.authorName,
    required this.authorAvatarUrl,
  });

  static List<Topic> getSampleTopics() {
    final now = DateTime.now();
    return [
      Topic(
        id: '1',
        title: '如何优雅地拒绝前任的复合请求？',
        tag: '恋爱脑撤退',
        likes: 89,
        comments: 3,
        createdAt: now.subtract(const Duration(hours: 2)),
        imageUrl: 'https://picsum.photos/seed/topic1/400/300',
        authorId: 'author_1',
        authorName: '小鹿',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
      ),
      Topic(
        id: '2',
        title: '职场上被刁难，该怎么高情商回怼？',
        tag: '职场回怼',
        likes: 67,
        comments: 6,
        createdAt: now.subtract(const Duration(hours: 5)),
        imageUrl: 'https://picsum.photos/seed/topic2/400/300',
        authorId: 'author_2',
        authorName: '阿杰',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
      ),
      Topic(
        id: '3',
        title: '异地恋快三年了，感觉越来越冷淡...',
        tag: '异地恋降温',
        likes: 124,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 8)),
        imageUrl: 'https://picsum.photos/seed/topic3/400/300',
        authorId: 'author_3',
        authorName: '星星',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/46.jpg',
      ),
      Topic(
        id: '4',
        title: '对方总说「你想多了」怎么破？',
        tag: '反PUA训练',
        likes: 156,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 1)),
        imageUrl: 'https://picsum.photos/seed/topic4/400/320',
        authorId: 'author_4',
        authorName: '柚子',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/47.jpg',
      ),
      Topic(
        id: '5',
        title: '暗恋的人发来一句「在吗」我该怎么回？',
        tag: '暗恋信号',
        likes: 203,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 3)),
        imageUrl: 'https://picsum.photos/seed/topic5/400/280',
        authorId: 'author_5',
        authorName: '阿树',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/33.jpg',
      ),
      Topic(
        id: '6',
        title: '分手后还总想联系怎么办',
        tag: '恋爱脑撤退',
        likes: 92,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 6)),
        imageUrl: 'https://picsum.photos/seed/topic6/400/350',
        authorId: 'author_6',
        authorName: '小满',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/48.jpg',
      ),
      Topic(
        id: '7',
        title: '领导当众否定我，事后怎么沟通？',
        tag: '职场回怼',
        likes: 78,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 4)),
        imageUrl: 'https://picsum.photos/seed/topic7/400/260',
        authorId: 'author_7',
        authorName: '林深',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/34.jpg',
      ),
      Topic(
        id: '8',
        title: '和对象视频时总没话说，正常吗',
        tag: '异地恋降温',
        likes: 112,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 10)),
        imageUrl: 'https://picsum.photos/seed/topic8/400/300',
        authorId: 'author_8',
        authorName: '晚风',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/49.jpg',
      ),
      Topic(
        id: '9',
        title: '被说「你太敏感了」是不是在 gaslight 我？',
        tag: '反PUA训练',
        likes: 189,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 12)),
        imageUrl: 'https://picsum.photos/seed/topic9/400/340',
        authorId: 'author_9',
        authorName: '清醒',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/50.jpg',
      ),
      Topic(
        id: '10',
        title: '喜欢的人点赞了我半年前的朋友圈',
        tag: '暗恋信号',
        likes: 267,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 7)),
        imageUrl: 'https://picsum.photos/seed/topic10/400/290',
        authorId: 'author_10',
        authorName: '心动',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/51.jpg',
      ),
      Topic(
        id: '11',
        title: '明知不该等却还在等 TA 回头',
        tag: '恋爱脑撤退',
        likes: 145,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 9)),
        imageUrl: 'https://picsum.photos/seed/topic11/400/310',
        authorId: 'author_11',
        authorName: '念念',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/52.jpg',
      ),
      Topic(
        id: '12',
        title: '同事总把锅甩给我，怎么怼回去？',
        tag: '职场回怼',
        likes: 98,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 11)),
        imageUrl: 'https://picsum.photos/seed/topic12/400/270',
        authorId: 'author_12',
        authorName: '硬气',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
      ),
      Topic(
        id: '13',
        title: '异地恋见面后分开的那天太难熬了',
        tag: '异地恋降温',
        likes: 178,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 15)),
        imageUrl: 'https://picsum.photos/seed/topic13/400/330',
        authorId: 'author_13',
        authorName: '小别',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/women/53.jpg',
      ),
      Topic(
        id: '14',
        title: '学会说「不」之后整个人都轻松了',
        tag: '反PUA训练',
        likes: 312,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 20)),
        imageUrl: 'https://picsum.photos/seed/topic14/400/300',
        authorId: 'author_14',
        authorName: '边界感',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
      ),
      Topic(
        id: '15',
        title: '不敢表白怕连朋友都做不成',
        tag: '暗恋信号',
        likes: 221,
        comments: 2,
        createdAt: now.subtract(const Duration(hours: 18)),
        imageUrl: 'https://picsum.photos/seed/topic15/400/280',
        authorId: 'author_15',
        authorName: '怂包',
        authorAvatarUrl: 'https://randomuser.me/api/portraits/men/37.jpg',
      ),
    ];
  }
}
